version: "3.9"

name: harmony-core

services:
  core-main:
    tty: true
    restart: always
    image: harmony/storage:latest
    container_name: harmony-core
    build: .
    ports:
      - 5002:5002
    env_file:
      - .env
    networks:
      - application
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/src/app
    command: air -c .air.toml
  
  db:
    image: postgres:alpine
    container_name: postgres-db
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - application
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis-pubsub
    ports:
      - 6379:6379
    networks:
      - application

networks:
  application:

volumes:
  postgres-db: